Repository camunda/camunda-modeler, pull requests merged in 2022-04, with the labels that each got.

#2875 Update app icon
  app/resources/favicon.png
  build/icon.icns
  build/icon.ico
  build/icon.png
Labels: needs review

#2874 feat: welcome tab telemetry
  client/src/app/EmptyTab.js
  client/src/plugins/usage-statistics/event-handlers/UserTrackedClickEventHandler.js
  client/src/plugins/usage-statistics/event-handlers/VersionInfoLinkOpenedEventHandler.js
  client/src/plugins/usage-statistics/event-handlers/__tests__/UserTrackedClickEventHandlerSpec.js
  client/src/plugins/usage-statistics/event-handlers/index.js
Labels: needs review

#2877 feat: support engine profile selection for DMN
  client/package-lock.json
  client/package.json
  client/src/app/tabs/EngineProfile.js
  client/src/app/tabs/__tests__/EngineProfile.cloud.dmn
  client/src/app/tabs/__tests__/EngineProfile.missing-patch.cloud.dmn
  client/src/app/tabs/__tests__/EngineProfile.missing-patch.platform.dmn
  client/src/app/tabs/__tests__/EngineProfile.namespace.dmn
  client/src/app/tabs/__tests__/EngineProfile.patch.cloud.dmn
  client/src/app/tabs/__tests__/EngineProfile.patch.platform.dmn
  client/src/app/tabs/__tests__/EngineProfile.platform.dmn
  client/src/app/tabs/__tests__/EngineProfile.unknown-version.cloud.dmn
  client/src/app/tabs/__tests__/EngineProfile.unknown-version.platform.dmn
  client/src/app/tabs/__tests__/EngineProfile.unknown.dmn
  client/src/app/tabs/__tests__/EngineProfile.vanilla.dmn
  client/src/app/tabs/__tests__/EngineProfileSpec.js
  client/src/app/tabs/cloud-dmn/DmnEditor.js
  client/src/app/tabs/cloud-dmn/__tests__/DmnEditorSpec.js
  client/src/app/tabs/cloud-dmn/modeler/DmnModeler.js
  client/src/app/tabs/dmn/DmnEditor.js
  client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
  client/src/app/tabs/dmn/modeler/DmnModeler.js
  client/test/bpmn-io-modelers/dmn/CloudDmnModelerSpec.js
  client/test/bpmn-io-modelers/dmn/DmnModelerSpec.js
  client/test/mocks/dmn-js/Modeler.js
Labels: needs review

#2881 Improve UX of deploy's remember credentials
  client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
  client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
  client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginOverlaySpec.js
  client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
Labels: needs review

#2888 fix: adjusted logging for toast notifications
  client/src/app/App.js
  client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
  client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
  client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
  client/src/plugins/update-checks/UpdateChecks.js
  client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
  client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
  client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
Labels: needs review

#2892 fix: DMN overview icons ignore pointer events
  client/src/app/tabs/dmn/OverviewContainer.less
Labels: needs review

#2884 feat(usage-statistics): track icons usage
  client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
  client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
Labels: needs review, metrics

#2898 fix: copy correct execution platform
  client/src/plugins/report-feedback/ClipboardCopySystemInfo.js
  client/src/plugins/report-feedback/__tests__/ClipboardCopySystemInfoSpec.js
Labels: needs review

#2900 chore: link to new forum homepage
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  client/src/app/tabs/MultiSheetTab.js
  client/src/plugins/report-feedback/ReportFeedbackOverlay.js
Labels: needs review

#2911 Open target=_blank links once
  app/lib/index.js
Labels: needs review

#2909 docs: update element template samples
  resources/element-templates/cloud-samples.json
  resources/element-templates/samples.json
Labels: needs review

#2914 chore(emptyTab): link to C8 intro blogPost
  client/src/app/EmptyTab.js
Labels: needs review

#2855 chore(ReleaseInfo): update to 5.0.0
  client/src/plugins/version-info/ReleaseInfo.js
Labels: needs review

#2890 Improve connection error messages in cloud deploy
  app/lib/zeebe-api.js
  app/test/spec/zeebe-api-spec.js
  client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
  client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
Labels: needs review

#2912 chore: add query params to camunda.com URLs
  client/src/app/EmptyTab.js
  client/src/app/tabs/EngineProfile.js
  client/src/app/tabs/__tests__/EngineProfileSpec.js
  client/src/plugins/privacy-preferences/constants.js
  client/src/plugins/report-feedback/ReportFeedbackOverlay.js
  client/src/plugins/version-info/VersionInfoOverlay.js
  client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstanceConfigOverlay.js
Labels: needs review

#2917 fix(App): use separate linting state
  client/src/app/App.js
  client/src/app/__tests__/AppSpec.js
  client/src/app/tabs/MultiSheetTab.js
Labels: needs review

#2915 fix(overlay): adjust max heights to always fit viewport
  client/src/plugins/report-feedback/ReportFeedbackOverlay.js
  client/src/shared/ui/overlay/Overlay.less
Labels: in progress

#2893 2873 reopen last tab startup
  app/lib/menu/menu-builder.js
Labels: needs review
