Repository camunda/camunda-modeler, pull requests merged in 2024-10, with the labels that each got.

#4576 Export images with webhook icon
  client/src/app/util/__tests__/generateImageSpec.js
  client/src/app/util/__tests__/webhook.svg
  package-lock.json
Labels: needs review

#4553 deps: bump to @camunda/improved-canvas@1.7.5
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review, dependencies

#4583 fix(package.json): use correct testing library version
  client/package.json
  package-lock.json
  package.json
Labels: needs review

#4589 ci: use macos-latest runner
  .github/workflows/BUILD_ON_DEMAND.yml
  .github/workflows/CI.yml
  .github/workflows/NIGHTLY.yml
  .github/workflows/RELEASE.yml
Labels: needs review, infrastructure

#4598 fix(linting-tab): display unaltered name or ID
  client/src/app/panel/tabs/linting/LintingTab.js
  client/src/app/panel/tabs/linting/__tests__/LintingTabSpec.js
Labels: needs review

#4602 deps(client): update @camunda/linting to v3.27.2
  client/package.json
  package-lock.json
Labels: needs review

#4599 fix: add explicit styles for welcome tab
  CHANGELOG.md
  client/src/app/EmptyTab.less
  client/src/app/primitives/TabLinks.js
  client/src/plugins/privacy-preferences/PrivacyPreferencesView.less
  client/src/plugins/update-checks/NewVersionInfoView.less
  client/src/shared/ui/overlay/Overlay.less
  client/src/styles/_base.less
  client/src/styles/_font.less
  client/src/styles/_forms.less
  client/src/styles/_modal.less
Labels: needs review

#4611 chore: simplify link-dependencies task
  tasks/link-dependencies.js
Labels: needs review

#4615 Fix dependencies linking
  tasks/link-dependencies.js
Labels: needs review

#4621 chore: remove flex-spacer from welcome tab
  client/src/app/EmptyTab.js
  client/src/app/EmptyTab.less
Labels: needs review

#4636 feat: add new alpha versions
  client/src/util/Engines.js
Labels: needs review

#4637 fix(errorTracking): add user configuration to sentry
  app/lib/util/__tests__/error-tracking-spec.js
  app/lib/util/error-tracking.js
  client/src/plugins/error-tracking/ErrorTracking.js
  client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
Labels: needs review

#4640 chore: bump puppeteer
  client/package.json
  package-lock.json
Labels: needs review, dependencies

#4639 Gracefully handle creating milestone with existing name
  .github/workflows/CREATE_MILESTONE.yml
Labels: needs review

#4634 chore: bump form-js deps
  client/package.json
  package-lock.json
Labels: needs review

#4643 chore: add v5.29.0 release info
  client/src/plugins/version-info/ReleaseInfo.js
Labels: needs review, release
