Repository camunda/camunda-modeler, pull requests merged in 2024-06, with the labels that each got.

#4326 Integrate DMN modeling improvements
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review

#4328 deps: bump to @camunda/linting@3.21.0
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review

#4330 Support placeholders in String and Text templates properties
  CHANGELOG.md
  client/package.json
  package-lock.json
  resources/element-templates/cloud-samples.json
Labels: needs review, ux, element templates

#4334 chore: update release info for v5.24.0
  client/src/plugins/version-info/ReleaseInfo.js
Labels: needs review

#4358 chore: use `@axe-core/react` in dev
  client/package.json
  client/src/index.js
  client/src/util/a11y.js
  package-lock.json
Labels: needs review

#4364 docs: make accessibility tests part of the integration test
  docs/.project/INTEGRATION_TEST.md
Labels: needs review

#4365 docs: update integration test to refer to the a11y plugin UI
  docs/.project/INTEGRATION_TEST.md
Labels: needs review

#4362 chore(.github): adjust PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs review

#4372 chore(PrivacyPolicy): add link styles
  client/src/plugins/privacy-preferences/PrivacyPreferencesView.js
  client/src/plugins/privacy-preferences/PrivacyPreferencesView.less
  client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesViewSpec.js
  client/src/plugins/privacy-preferences/constants.js
  client/src/styles/_base.less
  client/src/styles/_colors.less
Labels: needs review, a11y

#4377 fix: set document title
  app/lib/index.js
  client/public/index.html
Labels: needs review

#4379 Add accessible names and tabindex to code editors
  client/src/app/tabs/json/CodeMirror.js
  client/src/app/tabs/xml/CodeMirror.js
Labels: needs review

#4384 chore(ReleaseInfo): update to v5.25.0
  client/src/plugins/version-info/ReleaseInfo.js
Labels: needs review

#4391 deps: pin lerna version to `8.1.2`
  package-lock.json
  package.json
Labels: needs review

#4393 chore: fix link in changelog
  CHANGELOG.md
Labels: needs review

#4399 deps: update to @bpmn-io/feel-editor@1.6.1
  package-lock.json
Labels: needs review
