Repository camunda/camunda-modeler, pull requests merged in 2024-08, with the labels that each got.

#4440 chore: update release info for v5.26.0
  client/src/plugins/version-info/ReleaseInfo.js
Labels: needs review

#4447 chore: update docs
  docs/.project/INTEGRATION_TEST.md
  docs/.project/test.form.png
Labels: needs review, documentation

#4456 chore: update changelog
  CHANGELOG.md
Labels: needs review

#4468 deps: update BPMN modeling libraries
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review, dependencies

#4459 feat(cloud-bpmn): add variable outline tab
  client/package.json
  client/src/app/panel/tabs/linting/LintingTab.js
  client/src/app/panel/tabs/log/LogTab.js
  client/src/app/panel/tabs/variable-outline/VariableOutlineTab.js
  client/src/app/tabs/cloud-bpmn/BpmnEditor.js
  client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
  client/test/mocks/bpmn-js/Modeler.js
  package-lock.json
Labels: needs review

#4479 chore: rename flag to `disable-connector-templates`
  app/lib/index.js
Labels: needs review

#4485 deps: upgrade to `electron@31.4.0`
  CHANGELOG.md
  package-lock.json
  package.json
Labels: needs review
