Repository camunda/camunda-modeler, pull requests merged in 2025-03, with the labels that each got.

#4869 Fix links in the release notice
  .github/workflows/RELEASE.yml
Labels: needs review

#4875 deps: update to bpmn-js-properties-panel-v5.33.0
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: in progress

#4877 camunda self managed oauth not connecting
  app/lib/zeebe-api/zeebe-api.js
  app/test/spec/zeebe-api/zeebe-api-spec.js
Labels: needs review

#4880 docs: document Windows signing explicitly
  docs/.project/RELEASE_TEMPLATE.md
Labels: needs review

#4883 docs(project): update PATCH_RELEASE_TEMPLATE
  docs/.project/PATCH_RELEASE_TEMPLATE.md
Labels: needs review

#4884 ci: handle release issue reassignment correctly
  .github/workflows/RELEASE_ISSUE.yml
Labels: needs review, infrastructure

#4903 feat: mark Camunda 7.23 and Camunda 8.7 as latest
  client/src/util/Engines.js
  client/src/util/__tests__/EnginesSpec.js
Labels: needs review

#4902 deps: update to `@camunda/linting@3.36.0`, `bpmn-js-properties-panel@5.34.1`
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review

#4904 deps: bump form-js deps
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review, dependencies

#4906 feat: add resources integration
  app/lib/file-context/__tests__/file-context-spec.js
  app/lib/file-context/__tests__/fixtures/extensions/.process-application
  app/lib/file-context/processors/bpmnProcessor.js
  app/lib/file-context/processors/dmnProcessor.js
  app/lib/file-context/processors/formProcessor.js
  client/src/app/tabs/cloud-bpmn/BpmnEditor.js
  client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
  client/src/plugins/process-applications/ProcessApplications.js
  client/src/plugins/process-applications/ProcessApplicationsPlugin.js
  client/src/plugins/process-applications/ResourcesProvider.js
  client/src/plugins/process-applications/__tests__/ProcessApplicationsSpec.js
  client/src/plugins/process-applications/__tests__/ResourcesProviderSpec.js
Labels: needs review

#4911 Update package-lock
  package-lock.json
Labels: needs review

#4922 deps: update to `camunda-bpmn-js@5.7.1`
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review, dependencies

#4935 fix(process-applications): handle unsaved tab
  client/src/plugins/process-applications/ProcessApplications.js
  client/src/plugins/process-applications/__tests__/ProcessApplicationsSpec.js
Labels: needs review

#4942 deps(client): update @camunda/linting
  client/package.json
  package-lock.json
Labels: needs review, dependencies

#4938 fix: notifications are always on top
  client/src/app/notifications/Notification.less
  client/src/app/notifications/Notifications.less
Labels: needs review

#4944 fix(RPA): open fallback editor on invalid JSON
  client/src/app/tabs/rpa/RPAEditor.js
  client/src/app/tabs/rpa/__tests__/RPAEditorSpec.js
Labels: needs review

#4947 deps: bump form-js deps
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review
