Repository camunda/camunda-modeler, pull requests merged in 2025-02, with the labels that each got.

#4820 Fix: Wrong color used when applying from menu action #4756
  client/src/app/tabs/getEditMenu.js
Labels: bug

#4832 chore: bump form-js deps
  client/package.json
  package-lock.json
Labels: needs review

#4836 Suggest ad-hoc subprocess with new context pad
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: in progress

#4838 feat: support Camunda 8.8
  CHANGELOG.md
  client/src/util/Engines.js
Labels: needs review

#4841 fix: make text in tooltip selectable
  client/src/app/resizable-container/PropertiesPanelContainer.less
Labels: needs review

#4845 deps(client): update to `camunda-bpmn-js@5.6.0`
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review, dependencies

#4842 chore(app): correct type annotation
  app/lib/zeebe-api/zeebe-api.js
Labels: needs review

#4849 deps: update to `@camunda/linting@3.33.0`
  CHANGELOG.md
  client/package.json
  package-lock.json
Labels: needs review

#4846 Prepare v5.33 release info
  client/src/plugins/version-info/ReleaseInfo.js
Labels: needs review

#4865 chore(docs): update release issue template with Web Modeler deps update
  docs/.project/RELEASE_TEMPLATE.md
Labels: needs review, documentation
